### ISSUE TITLE
Commands without a docstring print ` - ` misaligned in formatted help text

### ISSUE THREAD

**Issue by CFiggers** [ianthehenry/cmd#3]
I notice that when a command doesn't have a docstring, its hyphen separator in the formatted help text prints misaligned from the other commands:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/55862180/231816461-dc451a9b-b0be-4103-88d6-8e930755b0d5.png">

It almost looks like this is done on purpose in `help.janet`:

https://github.com/ianthehenry/cmd/blob/03801e7f7855792974ef56d4173b72736607c5cf/src/help.janet#L102

If it wasn't for that `empty?` check, the hyphen would always align regardless. So that makes this behavior look intentional.

I'm curious why?

**Comment by ianthehenry** [comment]
Ah, this is because regular `command --help` doesn't print a separator when there's no docstring, so the `empty?` check prevents adding useless trailing whitespace. But `cmd/group` always prints the separator, even when there's no docstring. This is just a bug.

**Comment by ianthehenry** [comment]
Fixed in 96c617009d5d6a26e520da268ae0820cdf52992f
