### ISSUE TITLE
Breaks when compiled for Janet 1.30.0 using jpm quickbin

### ISSUE THREAD

**Issue by ryanslade** [ianthehenry/cmd#6]
For this example program:

```janet
(import cmd)

(cmd/main (cmd/fn
  [--greeting (optional :string "Hello")
   name :string]
  (printf "%s, %s!" greeting name)))
```

When run as a script using `janet main.janet` works as expected, but when compiled using `jpm quickbin main.janet example` and run we get this error:

```
error: bad slot #1, expected string, symbol, keyword or buffer, got nil
  in string/split [src/core/string.c] on line 445
  in is-probably-interpreter? [/opt/homebrew/Cellar/janet/1.30.0/lib/janet/cmd/util.janet] on line 78, column 12
  in args [/opt/homebrew/Cellar/janet/1.30.0/lib/janet/cmd/arg-parser.janet] on line 148, column 9
  in main [main.janet] on line 6, column 1
```

**Comment by ianthehenry** [comment]
Hmm, I thought I fixed this a while ago... 

Could you try updating to 1.1.0 and checking if the problem persists? That stack trace looks like it’s coming from an older `cmd`.

**Comment by ryanslade** [comment]
Perfect, that fixed it. I assumed I was already on the latest version since I upgrade to Janet 1.30.0 today and had to install `cmd` via `jpm` again. For some reason that seemed to install an older version.
